### ISSUE TITLE
ImportError: DLL load failed: 找不到指定的程序

### ISSUE THREAD

**Issue by yanchangqin** [ucas-vg/TinyBenchmark#10]
Excuse me, I encountered this error while running the program, how should I solve it?Did the compilation fail?
Traceback (most recent call last):
  File "D:/BaiduNetdiskDownload/tiny_face/TinyBenchmark-master/tiny_benchmark/tools/train_test_net.py", line 19, in <module>
    from maskrcnn_benchmark.engine.inference import inference
  File "D:\Users\86183\Anaconda3\envs\maskrcnn_benchmark\lib\site-packages\maskrcnn_benchmark-0.1-py3.7-win-amd64.egg\maskrcnn_benchmark\engine\inference.py", line 10, in <module>
    from tiny_benchmark.maskrcnn_benchmark.data.datasets.evaluation import evaluate
  File "D:\BaiduNetdiskDownload\tiny_face\TinyBenchmark-master\tiny_benchmark\maskrcnn_benchmark\data\datasets\evaluation\__init__.py", line 3, in <module>
    from .coco import coco_evaluation
  File "D:\BaiduNetdiskDownload\tiny_face\TinyBenchmark-master\tiny_benchmark\maskrcnn_benchmark\data\datasets\evaluation\coco\__init__.py", line 1, in <module>
    from .coco_eval import do_coco_evaluation
  File "D:\BaiduNetdiskDownload\tiny_face\TinyBenchmark-master\tiny_benchmark\maskrcnn_benchmark\data\datasets\evaluation\coco\coco_eval.py", line 10, in <module>
    from maskrcnn_benchmark.structures.boxlist_ops import boxlist_iou
  File "D:\Users\86183\Anaconda3\envs\maskrcnn_benchmark\lib\site-packages\maskrcnn_benchmark-0.1-py3.7-win-amd64.egg\maskrcnn_benchmark\structures\boxlist_ops.py", line 6, in <module>
    from tiny_benchmark.maskrcnn_benchmark.layers import nms as _box_nms
  File "D:\BaiduNetdiskDownload\tiny_face\TinyBenchmark-master\tiny_benchmark\maskrcnn_benchmark\layers\__init__.py", line 9, in <module>
    from .nms import nms
  File "D:\BaiduNetdiskDownload\tiny_face\TinyBenchmark-master\tiny_benchmark\maskrcnn_benchmark\layers\nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: DLL load failed: 找不到指定的程序。

**Comment by yanchangqin** [comment]
I've solved it!I deleted the build file and recompiled (python setup.py build develop), but I ran into a new problem: no instance of function template "THCCeilDiv" matches.Solution reference blog https://blog.csdn.net/tanmx219/article/details/87827035

**Comment by yinglang** [comment]
Sorry for I have not try on Windows, so this problem have never happened on my computer which is Ubuntu16.04, CUDA10.0/CUDA9.2, pytorch1.0.1. I suspect it may be a CUDA/pytorch version problem, can you tell me your CUDA version?
