### ISSUE TITLE
Colob 上执行报错 AttributeError: module 'torch._six' has no attribute 'PY3' 重启内核 无法解决

### ISSUE THREAD

**Issue by tianrking** [ucas-vg/TinyBenchmark#55]
Traceback (most recent call last):
  File "tools/train_test_net.py", line 8, in <module>
    from maskrcnn_benchmark.utils.env import setup_environment  # noqa F401 isort:skip
  File "/content/TinyBenchmark/tiny_benchmark/maskrcnn_benchmark/utils/env.py", line 4, in <module>
    from maskrcnn_benchmark.utils.imports import import_file
  File "/content/TinyBenchmark/tiny_benchmark/maskrcnn_benchmark/utils/imports.py", line 4, in <module>
    if torch._six.PY3:
AttributeError: module 'torch._six' has no attribute 'PY3'

**Comment by yxxxxxhh111** [comment]
same question
